In [ ]:
import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
data = pd.read_csv("/content/diabetes.csv")
data


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
x = data.iloc[:,[2,4]].values
y = data.iloc[:,8].values

In [ ]:
x

array([[ 72,   0],
       [ 66,   0],
       [ 64,   0],
       ...,
       [ 72, 112],
       [ 60,   0],
       [ 70,   0]])

In [ ]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [ ]:
# splitting the data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
x_train

array([[62,  0],
       [58, 94],
       [80,  0],
       ...,
       [65,  0],
       [74,  0],
       [82,  0]])

In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)

In [ ]:
x_train

array([[-0.40451932, -0.71823753],
       [-0.61509602,  0.08374747],
       [ 0.54307587, -0.71823753],
       ...,
       [-0.24658679, -0.71823753],
       [ 0.2272108 , -0.71823753],
       [ 0.64836422, -0.71823753]])

In [ ]:
x_test

array([[ 0.33249916, -0.71823753],
       [ 0.2272108 ,  0.13493801],
       [-0.40451932, -0.71823753],
       [ 0.12192245,  0.77481966],
       [-0.24658679, -0.71823753],
       [ 0.12192245, -0.37696732],
       [ 0.43778751,  0.74069264],
       [ 0.85894093,  0.61271631],
       [-0.61509602,  1.6279952 ],
       [ 0.12192245,  0.90279599],
       [ 0.33249916,  1.37204254],
       [ 0.33249916,  1.04783583],
       [ 0.2272108 , -0.71823753],
       [-0.93096108,  0.26291434],
       [ 0.12192245, -0.71823753],
       [-0.08865426, -0.71823753],
       [ 0.12192245,  0.39089067],
       [-1.03624944, -0.71823753],
       [ 0.85894093, -0.71823753],
       [-0.82567273, -0.01010184],
       [ 0.64836422, -0.71823753],
       [ 0.54307587, -0.71823753],
       [-3.66845828, -0.71823753],
       [ 0.64836422, -0.71823753],
       [-0.19394261,  0.47620822],
       [-0.50980767, -0.71823753],
       [ 0.33249916, -0.71823753],
       [ 0.96422928,  0.47620822],
       [-0.19394261,

In [ ]:
# Fitting Logistic Regression to the training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
LogisticRegression(C=1.0,class_weight=None,fit_intercept=True,intercept_scaling=1,l1_ratio=None,max_iter=100,multi_class='warn',n_jobs=None,penalty='l2',random_state=0,solver='warn',tol=0.0001,verbose=0,warm_start=False)


LogisticRegression(multi_class='warn', random_state=0, solver='warn')

In [ ]:
# predicting the test set result
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn import metrics
cm = metrics.confusion_matrix(y_test,y_pred)
cm

array([[129,   1],
       [ 58,   4]])

In [ ]:
TP = 129
FP = 1
FN = 58
TN = 4

In [ ]:
accuaracy = (TP+TN)/(TP++FP+FN+TN)
accuaracy

0.6927083333333334

In [ ]:
print(f"accuaracy : {metrics.accuracy_score(y_test,y_pred)}")

accuaracy : 0.6927083333333334


In [ ]:
print(f"precission : {metrics.precision_score(y_test,y_pred)}")

precission : 0.8


In [ ]:
print(f"recall : {metrics.recall_score(y_test,y_pred)}")

recall : 0.06451612903225806


In [ ]:
RECALL = TP/(TP+FN)
RECALL

0.6898395721925134

In [ ]:
4/5

0.8

In [ ]:
# [200,600]
# [150,50]
tp=200
tn=50
fp=150
fn=600
acc=tp/(tp+fp)
print(acc)
rec = tp/(tp+fn)
print(rec)

0.5714285714285714
0.25
